### ISSUE TITLE
A specific bug

### ISSUE THREAD

**Issue by jescalan** [nuxodin/ie11CustomProperties#23]
After a truly unfortunate amount of effort testing and debugging in IE11, I think I have tracked down what appears to be a consistent bug with a clear minimal reproduction. It happens when you have a media query which contains a pseudo-selector which contains a custom property, in an external stylesheet. For example:

```css
@media (max-width: 100px) {
  .foo:hover {
    background: var(--red);
  }
}
```

With any code that fits this pattern, dropped on to the page using an external stylesheet will break IE's css parsing silently, of course, causing it and any css following in its own stylesheet not to render.

I inspected the output of the parsed styles and I think the actual error is fairly clear - it ends up placing an `-ieVar-` string before the css selector, rather than before the property as it does when a media query is not present under the same scenario. For the example above, the output would look like this:

```css
@media (max-width: 100px) {
  -ieVar-.foo:hover {
    background: var(--red);
  }
}
```

It should instead render like this:

```css
@media (max-width: 100px) {
  .foo:hover {
    -ieVar-background: var(--red);
    background: var(--red);
  }
}
```

I would be happy to look into the cause and try to contribute a fix, just wanted to log it here and get an opinion first 😁
