### ISSUE TITLE
Is there a method to force the script to re-calculate?

### ISSUE THREAD

**Issue by FrDH** [nuxodin/ie11CustomProperties#59]
Hi,
In my case, I add a classname to the body with javascript that changes the value of a css variable, but the polyfill does not pick up on this change. 

For example, the text should turn red after adding the classname "red" to the `<body>` with javascript:
````css
:root {
   --color: blue;
}
.red {
   --color: red;
}

body {
   color: var(--color);
}
````
````js
document.body.classList.add("red");
````

I can imagine it is impossible for the polyfill to automatically pick up this change (except for maybe adding an `MutationObserver` for the classList on each and every DOM element...), so therefor a method to force the script to re-run would come in handy. Something like:
````js
document.body.classList.add("red");
ie11CustomProperties.reRun();
````
