### ISSUE TITLE
script failed on local css links

### ISSUE THREAD

**Issue by viT-1** [nuxodin/ie11CustomProperties#90]
** Description **  
Just run test.htm directly from disk drive
with css link to local file in same directory.

Error on L636 (fetchCss function): `request.open('GET', url);`

** Version **  
4.1.0

** To Reproduce **  
ie11failedVar.css:
```css
[iam-body] {
	--myColor: green;
}

[iam-p] {
	color: var(--myColor);
}
```

ie11failedVar.htm:
```html
<link rel="stylesheet" type="text/css" href="ie11failedVar.css" />
<script>window.MSInputMethodContext && document.documentMode && document.write('<script src="https://cdn.jsdelivr.net/npm/ie11-custom-properties@4.1.0/ie11CustomProperties.js"><\/script>');</script>
<body iam-body>
	<p iam-p>Test green</p>
	<p>Not green</p>
</body>
```
