### ISSUE TITLE
changed name of css variable & css variable which use another one

### ISSUE THREAD

**Issue by viT-1** [nuxodin/ie11CustomProperties#93]
** Description **  
Calculation isn't working if css variable uses another variable.
Such as (Title 3 in [example](https://vit-1.github.io/iAMcss-samples/v3/iam-collapser/)):
```css
[iam-collapser] {
-ieVar--ie-clr-shoal-back: hsla(var(--thm-hue), var(--thm-sat), 28%, 1);
-ie-clr-rase-front: hsla(215, 20%, 56%, 1);
-ie-iam-collapser-border-color: var(--clr-base-front);
}

[iam-collapser-header] {
border-top: solid var(--thin) var(--iam-collapser-border-color);
}
```

```html
<div class="iecp-u4" role="structure" style="-ie-thm-hue: 30;" iam-collapser="" iecp-needed="true">
<header class="iecp-u13" role="sectionhead" iam-collapser-header="is-open:true is-disabled:false" iecp-needed="true">Title 3</header>
...
</div>
```

** Version **  
nuxodin/ie11CustomProperties@4.1.0/ie11CustomProperties.js

** To Reproduce ** 
[Collapser with "Title 3"](https://vit-1.github.io/iAMcss-samples/v3/iam-collapser/) should use inline style with css variable.

I know this project is abandined, but may be you can help with workaround?
